apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
     - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: navaneethvinod/user-service
      context: user-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: navaneethvinod/product-service
      context: product-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
  