apiVersion: skaffold/v3
kind: Config

build:
  local:
    push: false
  artifacts:
    - image: navaneethvinod/user-service
      context: user-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .

    - image: navaneethvinod/product-service
      context: product-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: navaneethvinod/order-service
      context: order-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: navaneethvinod/api-gateway
      context: api-gateway
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .

manifests:
  rawYaml:
    - ./infra/k8s/*

# apiVersion: skaffold/v3
# kind: Config
# build:
#   artifacts:
#     - image: navaneethvinod/user-service
#       context: ./user-service
#       sync:
#         manual:
#           - src: ./src/*/.js
#             dest: .
#       docker:
#         dockerfile: Dockerfile
#     - image: navaneethvinod/product-service
#       context: ./product-service
#       sync:
#         manual:
#           - src: ./src/*/.js
#             dest: .
#       docker:
#         dockerfile: Dockerfile
#   local:
#     push: false
# manifests:
#   rawYaml:
#     - ./infra/k8s/*
# deploy: 
#   kubectl: {}